name: Build and Tag Containers On Chart Release

on:
  release:
    types: [created]

jobs:
  cas-nginx-sidecar-build:
    if: startsWith(github.ref, 'refs/tags/nginx-sidecar-')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the tag name
        id: get_tag_name
        run: echo ::set-output name=CHART_VERSION::${GITHUB_REF/refs\/tags\/nginx-sidecar-/}
      - uses: RafikFarhad/push-to-gcr-github-action@v4.1.0
        with:
          gcloud_service_key: ${{ secrets.GCR_KEY }}
          project_id: ggl-cas-storage
          image_name: cas-nginx
          image_tag: latest,${{ steps.get_tag_name.outputs.CHART_VERSION }}
          dockerfile: nginx-sidecar/Dockerfile
          context: nginx-sidecar
