name: Build Nginx Image

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  cas-nginx-sidecar-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build cas-nginx
        uses: ./.github/actions/build-nginx-image
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
