name: Publish @bcgov-cas packages with lerna monorepo
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org/"
          cache: "yarn"
          cache-dependency-path: yarn.lock
          scope: "bcgov-cas"
      - name: Install lerna
        run: yarn
      - name: Install dependencies for all packages
        run: yarn lerna bootstrap
      - name: Use Lerna to publish packages
        run: yarn lerna publish from-package --no-verify-access --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
